export interface SopMasterItem {
  number: string;
  title: string;
  dept: string;
  standards: string[];
  category?: string;
}

export const SOP_MASTER_LIST: SopMasterItem[] = [
  // PRE-ANALYTICAL (25)
  { number: "SOP-PRE-001", title: "Patient Identification and Registration", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-PRE-002", title: "Request Form Verification and Test Order Entry", dept: "PRE_ANALYTICAL", standards: ["NABL","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-PRE-003", title: "Patient Consent and Confidentiality", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "COMPLIANCE" },
  { number: "SOP-PRE-004", title: "Venipuncture — Adult Blood Collection", dept: "PHLEBOTOMY", standards: ["NABL","CAP","ISO_15189","CLSI"], category: "CLINICAL" },
  { number: "SOP-PRE-005", title: "Capillary Blood Collection (Finger Prick)", dept: "PHLEBOTOMY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-PRE-006", title: "Paediatric Blood Collection", dept: "PHLEBOTOMY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-PRE-007", title: "Neonatal Blood Collection", dept: "PHLEBOTOMY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-PRE-008", title: "Urine Sample Collection — Midstream", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-PRE-009", title: "24-Hour Urine Collection", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-PRE-010", title: "Stool Sample Collection", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-PRE-011", title: "Sputum Collection for Microbiological Testing", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-PRE-012", title: "Throat and Nasal Swab Collection", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-PRE-013", title: "Wound and Pus Swab Collection", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-PRE-014", title: "Cerebrospinal Fluid (CSF) Handling", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "CLINICAL" },
  { number: "SOP-PRE-015", title: "Bone Marrow Sample Handling", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-PRE-016", title: "Semen Analysis Sample Collection", dept: "PRE_ANALYTICAL", standards: ["NABL","WHO"], category: "CLINICAL" },
  { number: "SOP-PRE-017", title: "Biopsy Tissue Handling and Fixation", dept: "HISTOPATHOLOGY", standards: ["NABL","CAP","ISO_15189"], category: "CLINICAL" },
  { number: "SOP-PRE-018", title: "Sample Labelling and Barcoding", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-PRE-019", title: "Specimen Transport — Internal", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-PRE-020", title: "Specimen Transport — External / Home Collection", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-PRE-021", title: "Cold Chain Management for Specimens", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-PRE-022", title: "Sample Rejection Criteria and Procedure", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-PRE-023", title: "Specimen Receipt and Accessioning", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-PRE-024", title: "Sample Centrifugation Procedure", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-PRE-025", title: "Fasting Requirements and Patient Preparation Instructions", dept: "PRE_ANALYTICAL", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  // BIOCHEMISTRY (15)
  { number: "SOP-BIO-001", title: "Biochemistry Analyser — Operation and Maintenance", dept: "BIOCHEMISTRY", standards: ["NABL","CAP","ISO_15189"], category: "CLINICAL" },
  { number: "SOP-BIO-002", title: "Calibration of Biochemistry Analyser", dept: "BIOCHEMISTRY", standards: ["NABL","CAP","ISO_15189","CLSI"], category: "QUALITY" },
  { number: "SOP-BIO-003", title: "Quality Control — Biochemistry (Westgard Rules)", dept: "BIOCHEMISTRY", standards: ["NABL","CAP","ISO_15189","CLSI"], category: "QUALITY" },
  { number: "SOP-BIO-004", title: "Liver Function Tests (LFT) — Procedure", dept: "BIOCHEMISTRY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-BIO-005", title: "Kidney Function Tests (KFT/RFT) — Procedure", dept: "BIOCHEMISTRY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-BIO-006", title: "Lipid Profile Testing Procedure", dept: "BIOCHEMISTRY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-BIO-007", title: "Diabetes Testing — Blood Glucose, HbA1c, OGTT", dept: "BIOCHEMISTRY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-BIO-008", title: "Thyroid Function Tests (TFT) — Procedure", dept: "BIOCHEMISTRY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-BIO-009", title: "Electrolytes Testing — Na, K, Cl, Bicarbonate", dept: "BIOCHEMISTRY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-BIO-010", title: "Cardiac Biomarkers — Troponin, CK-MB, BNP", dept: "BIOCHEMISTRY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-BIO-011", title: "Tumour Markers Panel — Procedure", dept: "BIOCHEMISTRY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-BIO-012", title: "Hormone Assays — Reproductive Panel", dept: "BIOCHEMISTRY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-BIO-013", title: "Vitamin D and B12 Assay Procedure", dept: "BIOCHEMISTRY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-BIO-014", title: "Urine Routine and Microscopy Examination", dept: "BIOCHEMISTRY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-BIO-015", title: "Point-of-Care Testing (POCT) Management", dept: "BIOCHEMISTRY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  // HAEMATOLOGY (12)
  { number: "SOP-HAE-001", title: "Haematology Analyser — Operation and Maintenance", dept: "HAEMATOLOGY", standards: ["NABL","CAP","ISO_15189"], category: "CLINICAL" },
  { number: "SOP-HAE-002", title: "Complete Blood Count (CBC) Procedure", dept: "HAEMATOLOGY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-HAE-003", title: "Peripheral Blood Smear Preparation and Examination", dept: "HAEMATOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-HAE-004", title: "Erythrocyte Sedimentation Rate (ESR) Testing", dept: "HAEMATOLOGY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-HAE-005", title: "Coagulation Testing — PT, aPTT, INR", dept: "HAEMATOLOGY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-HAE-006", title: "Reticulocyte Count Procedure", dept: "HAEMATOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-HAE-007", title: "HbA1c by HPLC — Haematology Method", dept: "HAEMATOLOGY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-HAE-008", title: "Blood Group and Rh Typing", dept: "HAEMATOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-HAE-009", title: "Direct Coombs Test Procedure", dept: "HAEMATOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-HAE-010", title: "Malaria Parasite Detection — Smear and RDT", dept: "HAEMATOLOGY", standards: ["NABL","WHO"], category: "CLINICAL" },
  { number: "SOP-HAE-011", title: "Bone Marrow Aspiration Slide Review", dept: "HAEMATOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-HAE-012", title: "Quality Control — Haematology", dept: "HAEMATOLOGY", standards: ["NABL","CAP","ISO_15189","CLSI"], category: "QUALITY" },
  // MICROBIOLOGY (15)
  { number: "SOP-MIC-001", title: "Culture Media Preparation and Quality Control", dept: "MICROBIOLOGY", standards: ["NABL","CAP","ISO_15189"], category: "CLINICAL" },
  { number: "SOP-MIC-002", title: "Blood Culture — Collection and Processing", dept: "MICROBIOLOGY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-MIC-003", title: "Urine Culture and Sensitivity Testing", dept: "MICROBIOLOGY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-MIC-004", title: "Sputum Culture — AFB and General", dept: "MICROBIOLOGY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-MIC-005", title: "Wound and Pus Culture Procedure", dept: "MICROBIOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-MIC-006", title: "Antibiotic Sensitivity Testing (AST) — Kirby-Bauer", dept: "MICROBIOLOGY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-MIC-007", title: "Gram Staining Procedure", dept: "MICROBIOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-MIC-008", title: "AFB Staining (Ziehl-Neelsen) Procedure", dept: "MICROBIOLOGY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-MIC-009", title: "Stool Culture — Enteric Pathogens", dept: "MICROBIOLOGY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-MIC-010", title: "Fungal Culture and Identification", dept: "MICROBIOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-MIC-011", title: "CSF Culture and Analysis", dept: "MICROBIOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-MIC-012", title: "Rapid Antigen Tests — Strep, Influenza, COVID", dept: "MICROBIOLOGY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-MIC-013", title: "MRSA and MDR Organism Screening", dept: "MICROBIOLOGY", standards: ["NABL","CAP","CLSI"], category: "CLINICAL" },
  { number: "SOP-MIC-014", title: "Biosafety in Microbiology — BSL-2 Procedures", dept: "SAFETY", standards: ["NABL","CAP","WHO","ISO_15189"], category: "SAFETY" },
  { number: "SOP-MIC-015", title: "Decontamination and Autoclave Operation", dept: "MICROBIOLOGY", standards: ["NABL","CAP","WHO"], category: "SAFETY" },
  // MOLECULAR (8)
  { number: "SOP-MOL-001", title: "DNA/RNA Extraction Procedure", dept: "MOLECULAR", standards: ["NABL","CAP","ISO_15189"], category: "CLINICAL" },
  { number: "SOP-MOL-002", title: "RT-PCR Setup and Operation", dept: "MOLECULAR", standards: ["NABL","CAP","ISO_15189"], category: "CLINICAL" },
  { number: "SOP-MOL-003", title: "COVID-19 RT-PCR Testing Procedure", dept: "MOLECULAR", standards: ["NABL","WHO"], category: "CLINICAL" },
  { number: "SOP-MOL-004", title: "TB — CBNAAT/GeneXpert Testing", dept: "MOLECULAR", standards: ["NABL","WHO"], category: "CLINICAL" },
  { number: "SOP-MOL-005", title: "HPV Genotyping Procedure", dept: "MOLECULAR", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-MOL-006", title: "Prevention of PCR Contamination", dept: "MOLECULAR", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-MOL-007", title: "Molecular QC — Controls and Validation", dept: "MOLECULAR", standards: ["NABL","CAP","CLSI"], category: "QUALITY" },
  { number: "SOP-MOL-008", title: "Next Generation Sequencing — Sample Preparation", dept: "MOLECULAR", standards: ["NABL","CAP"], category: "CLINICAL" },
  // IMMUNOLOGY (8)
  { number: "SOP-IMM-001", title: "ELISA Procedure — General Protocol", dept: "IMMUNOLOGY", standards: ["NABL","CAP","ISO_15189"], category: "CLINICAL" },
  { number: "SOP-IMM-002", title: "HIV Testing — ICTC Protocol", dept: "IMMUNOLOGY", standards: ["NABL","WHO"], category: "CLINICAL" },
  { number: "SOP-IMM-003", title: "Hepatitis B and C Serology Testing", dept: "IMMUNOLOGY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-IMM-004", title: "VDRL/RPR — Syphilis Serology", dept: "IMMUNOLOGY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-IMM-005", title: "Widal Test and Typhidot Procedure", dept: "IMMUNOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-IMM-006", title: "ANA and Autoimmune Antibody Testing", dept: "IMMUNOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-IMM-007", title: "Immunofluorescence Microscopy Procedure", dept: "IMMUNOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-IMM-008", title: "Flow Cytometry — CD4 Count Procedure", dept: "IMMUNOLOGY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  // HISTOPATHOLOGY (8)
  { number: "SOP-HIS-001", title: "Biopsy Tissue Processing and Embedding", dept: "HISTOPATHOLOGY", standards: ["NABL","CAP","ISO_15189"], category: "CLINICAL" },
  { number: "SOP-HIS-002", title: "Microtomy and Section Cutting", dept: "HISTOPATHOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-HIS-003", title: "Haematoxylin and Eosin (H&E) Staining", dept: "HISTOPATHOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-HIS-004", title: "Special Stains — PAS, Masson Trichrome, etc.", dept: "HISTOPATHOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-HIS-005", title: "Immunohistochemistry (IHC) Procedure", dept: "HISTOPATHOLOGY", standards: ["NABL","CAP","ISO_15189"], category: "CLINICAL" },
  { number: "SOP-HIS-006", title: "PAP Smear Preparation and Reporting", dept: "HISTOPATHOLOGY", standards: ["NABL","CAP","WHO"], category: "CLINICAL" },
  { number: "SOP-HIS-007", title: "FNAC Sample Processing and Reporting", dept: "HISTOPATHOLOGY", standards: ["NABL","CAP"], category: "CLINICAL" },
  { number: "SOP-HIS-008", title: "Tissue Archiving and Block Storage", dept: "HISTOPATHOLOGY", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  // QUALITY MANAGEMENT (20)
  { number: "SOP-QMS-001", title: "Document Control and Management", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-002", title: "Internal Quality Audit Procedure", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-003", title: "External Quality Assessment (EQAS/PT) Program", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-004", title: "Non-Conformance and Corrective Action (CAPA)", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-005", title: "Customer Complaint Handling", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-006", title: "Uncertainty of Measurement", dept: "QUALITY", standards: ["NABL","ISO_15189","CLSI"], category: "QUALITY" },
  { number: "SOP-QMS-007", title: "Method Validation and Verification Procedure", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189","CLSI"], category: "QUALITY" },
  { number: "SOP-QMS-008", title: "Measurement Traceability", dept: "QUALITY", standards: ["NABL","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-009", title: "Reference Interval Establishment and Verification", dept: "QUALITY", standards: ["NABL","CAP","CLSI"], category: "QUALITY" },
  { number: "SOP-QMS-010", title: "IQC — Westgard Multi-Rules Application", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189","CLSI"], category: "QUALITY" },
  { number: "SOP-QMS-011", title: "Laboratory Risk Management", dept: "QUALITY", standards: ["NABL","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-012", title: "Critical Values Reporting Procedure", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-013", title: "Turnaround Time Monitoring and Management", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-014", title: "Management Review Meeting Procedure", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-015", title: "Staff Competency Assessment", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-016", title: "Laboratory Information System (LIS) Validation", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-017", title: "Outsourced Testing and Referral Laboratory Management", dept: "QUALITY", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-018", title: "Procedure for Handling Near-Miss Events", dept: "QUALITY", standards: ["NABL","ISO_15189"], category: "QUALITY" },
  { number: "SOP-QMS-019", title: "Patient Safety Goals in Laboratory", dept: "QUALITY", standards: ["NABL","CAP"], category: "QUALITY" },
  { number: "SOP-QMS-020", title: "Quality Indicators and KPI Monitoring", dept: "QUALITY", standards: ["NABL","ISO_15189","WHO"], category: "QUALITY" },
  // EQUIPMENT (10)
  { number: "SOP-EQP-001", title: "Equipment Procurement and Qualification", dept: "EQUIPMENT", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-EQP-002", title: "Equipment Calibration Programme", dept: "EQUIPMENT", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-EQP-003", title: "Preventive Maintenance Programme", dept: "EQUIPMENT", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-EQP-004", title: "Equipment Breakdown and Repair Management", dept: "EQUIPMENT", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-EQP-005", title: "Refrigerator and Freezer Temperature Monitoring", dept: "EQUIPMENT", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-EQP-006", title: "Centrifuge Operation and Maintenance", dept: "EQUIPMENT", standards: ["NABL","CAP"], category: "OPERATIONAL" },
  { number: "SOP-EQP-007", title: "Autoclave Validation and Monitoring", dept: "EQUIPMENT", standards: ["NABL","CAP","WHO"], category: "SAFETY" },
  { number: "SOP-EQP-008", title: "Analytical Balance — Calibration and Use", dept: "EQUIPMENT", standards: ["NABL","ISO_15189"], category: "QUALITY" },
  { number: "SOP-EQP-009", title: "Biosafety Cabinet — Operation and Certification", dept: "EQUIPMENT", standards: ["NABL","CAP","WHO"], category: "SAFETY" },
  { number: "SOP-EQP-010", title: "Water Quality Management — Type I, II, III", dept: "EQUIPMENT", standards: ["NABL","CAP","CLSI"], category: "QUALITY" },
  // SAFETY (12)
  { number: "SOP-SAF-001", title: "Standard Precautions and PPE Usage", dept: "SAFETY", standards: ["NABL","CAP","WHO"], category: "SAFETY" },
  { number: "SOP-SAF-002", title: "Biomedical Waste Management — BMW Rules 2016", dept: "SAFETY", standards: ["NABL","CAP"], category: "SAFETY" },
  { number: "SOP-SAF-003", title: "Needlestick and Sharps Injury Protocol", dept: "SAFETY", standards: ["NABL","CAP","WHO"], category: "SAFETY" },
  { number: "SOP-SAF-004", title: "Chemical Safety and MSDS Management", dept: "SAFETY", standards: ["NABL","CAP"], category: "SAFETY" },
  { number: "SOP-SAF-005", title: "Fire Safety and Emergency Evacuation", dept: "SAFETY", standards: ["NABL","CAP"], category: "SAFETY" },
  { number: "SOP-SAF-006", title: "Spillage — Biohazardous Material Management", dept: "SAFETY", standards: ["NABL","CAP","WHO"], category: "SAFETY" },
  { number: "SOP-SAF-007", title: "Hand Hygiene — WHO 5 Moments Protocol", dept: "SAFETY", standards: ["NABL","CAP","WHO"], category: "SAFETY" },
  { number: "SOP-SAF-008", title: "Hazardous Chemical Storage and Handling", dept: "SAFETY", standards: ["NABL","CAP"], category: "SAFETY" },
  { number: "SOP-SAF-009", title: "Laboratory Safety Inspection Checklist", dept: "SAFETY", standards: ["NABL","CAP","ISO_15189"], category: "SAFETY" },
  { number: "SOP-SAF-010", title: "Radiation Safety — X-ray and Isotope Handling", dept: "SAFETY", standards: ["NABL"], category: "SAFETY" },
  { number: "SOP-SAF-011", title: "Electrical Safety in the Laboratory", dept: "SAFETY", standards: ["NABL","CAP"], category: "SAFETY" },
  { number: "SOP-SAF-012", title: "Pandemic Preparedness and Outbreak Response", dept: "SAFETY", standards: ["NABL","WHO"], category: "SAFETY" },
  // ADMINISTRATION (10)
  { number: "SOP-ADM-001", title: "Staff Recruitment and Onboarding", dept: "ADMINISTRATION", standards: ["NABL","ISO_15189"], category: "HR" },
  { number: "SOP-ADM-002", title: "Training and Continuing Education Programme", dept: "ADMINISTRATION", standards: ["NABL","CAP","ISO_15189"], category: "HR" },
  { number: "SOP-ADM-003", title: "Leave and Attendance Management", dept: "ADMINISTRATION", standards: ["INTERNAL"], category: "HR" },
  { number: "SOP-ADM-004", title: "Confidentiality and Data Privacy Policy", dept: "ADMINISTRATION", standards: ["NABL","ISO_15189"], category: "COMPLIANCE" },
  { number: "SOP-ADM-005", title: "Visitor and External Personnel Policy", dept: "ADMINISTRATION", standards: ["NABL","CAP","ISO_15189"], category: "COMPLIANCE" },
  { number: "SOP-ADM-006", title: "Conflict of Interest Declaration", dept: "ADMINISTRATION", standards: ["NABL","CAP"], category: "COMPLIANCE" },
  { number: "SOP-ADM-007", title: "Procurement of Consumables and Reagents", dept: "ADMINISTRATION", standards: ["NABL","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-ADM-008", title: "Reagent and Chemical Inventory Management", dept: "ADMINISTRATION", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-ADM-009", title: "Supplier Evaluation and Approved Vendor List", dept: "ADMINISTRATION", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-ADM-010", title: "Budget Planning and Cost Control", dept: "ADMINISTRATION", standards: ["INTERNAL"], category: "OPERATIONAL" },
  // POST-ANALYTICAL (10)
  { number: "SOP-POST-001", title: "Result Verification and Authorisation", dept: "POST_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-POST-002", title: "Report Generation and Dispatch Procedure", dept: "POST_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-POST-003", title: "Delta Check Procedure", dept: "POST_ANALYTICAL", standards: ["NABL","CAP","CLSI"], category: "QUALITY" },
  { number: "SOP-POST-004", title: "Critical Values — Notification and Documentation", dept: "POST_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-POST-005", title: "Report Amendment and Correction Procedure", dept: "POST_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-POST-006", title: "Verbal and Telephonic Result Reporting", dept: "POST_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "QUALITY" },
  { number: "SOP-POST-007", title: "Specimen Retention and Storage Policy", dept: "POST_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-POST-008", title: "Sample Disposal After Testing", dept: "POST_ANALYTICAL", standards: ["NABL","CAP"], category: "SAFETY" },
  { number: "SOP-POST-009", title: "Digital Report Delivery — WhatsApp, Email, Portal", dept: "POST_ANALYTICAL", standards: ["NABL"], category: "OPERATIONAL" },
  { number: "SOP-POST-010", title: "Patient Result Inquiry Handling", dept: "POST_ANALYTICAL", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  // IT (8)
  { number: "SOP-IT-001", title: "Laboratory Information System (LIS) Access Control", dept: "IT", standards: ["NABL","CAP","ISO_15189"], category: "COMPLIANCE" },
  { number: "SOP-IT-002", title: "Data Backup and Recovery Procedure", dept: "IT", standards: ["NABL","CAP","ISO_15189"], category: "COMPLIANCE" },
  { number: "SOP-IT-003", title: "Cyber Security and Anti-Virus Policy", dept: "IT", standards: ["NABL"], category: "COMPLIANCE" },
  { number: "SOP-IT-004", title: "System Downtime Contingency Plan", dept: "IT", standards: ["NABL","CAP","ISO_15189"], category: "OPERATIONAL" },
  { number: "SOP-IT-005", title: "Patient Data Retention and Archival Policy", dept: "IT", standards: ["NABL","ISO_15189"], category: "COMPLIANCE" },
  { number: "SOP-IT-006", title: "Electronic Signature and Report Authentication", dept: "IT", standards: ["NABL","CAP"], category: "COMPLIANCE" },
  { number: "SOP-IT-007", title: "Interface Between Analyser and LIS", dept: "IT", standards: ["NABL","CAP"], category: "OPERATIONAL" },
  { number: "SOP-IT-008", title: "User Access Audit Log Review", dept: "IT", standards: ["NABL","CAP"], category: "COMPLIANCE" },
];
