import { Injectable, BadRequestException, NotFoundException } from "@nestjs/common";
import { PrismaService } from "../../../prisma/prisma.service";
import { JournalService } from "./journal.service";

export interface StatutoryObligation {
  type: string;
  label: string;
  period: string;
  dueDate: Date;
  status: string;
  amount: number;
  challanNumber?: string;
  paymentDate?: Date;
}

@Injectable()
export class ComplianceService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly journalService: JournalService,
  ) {}

  // ── Statutory obligation definitions ───────────────────────────────────
  private readonly obligations = [
    { type: "TDS_192", label: "TDS u/s 192 - Salary", dayOfMonth: 7 },
    { type: "TDS_194C", label: "TDS u/s 194C - Contractor", dayOfMonth: 7 },
    { type: "TDS_194J", label: "TDS u/s 194J - Professional", dayOfMonth: 7 },
    { type: "PF", label: "Provident Fund", dayOfMonth: 15 },
    { type: "ESIC", label: "ESIC Contribution", dayOfMonth: 15 },
    { type: "PT", label: "Professional Tax", dayOfMonth: 20 },
  ];

  // ── Ledger code mapping for statutory types ────────────────────────────
  private readonly ledgerCodeMap: Record<string, string> = {
    TDS_192: "2100",
    TDS_194C: "2100",
    TDS_194J: "2100",
    PF: "2200",       // PF Payable - Employee (combined)
    ESIC: "2300",     // ESIC Payable - Employee (combined)
    PT: "2400",       // Professional Tax Payable
  };

  // ── Get Compliance Calendar ────────────────────────────────────────────
  async getComplianceCalendar(tenantId: string, month?: number, year?: number) {
    const now = new Date();
    const targetMonth = month ?? (now.getMonth() + 1);
    const targetYear = year ?? now.getFullYear();
    const period = `${targetYear}-${String(targetMonth).padStart(2, "0")}`;

    // Check if statutory payments exist for this period
    const existingPayments = await this.prisma.statutoryPayment.findMany({
      where: { tenantId, period },
    });

    const existingMap = new Map(existingPayments.map(p => [p.type, p]));

    // Auto-generate if not exists for current month
    const calendar: StatutoryObligation[] = [];
    const createdRecords: any[] = [];

    for (const ob of this.obligations) {
      if (existingMap.has(ob.type)) {
        const existing = existingMap.get(ob.type)!;
        calendar.push({
          type: ob.type,
          label: ob.label,
          period,
          dueDate: existing.dueDate,
          status: existing.status,
          amount: Number(existing.amount),
          challanNumber: existing.challanNumber ?? undefined,
          paymentDate: existing.paymentDate ?? undefined,
        });
      } else {
        // Due date is in the FOLLOWING month
        const followingMonth = targetMonth === 12 ? 1 : targetMonth + 1;
        const followingYear = targetMonth === 12 ? targetYear + 1 : targetYear;
        const dueDate = new Date(followingYear, followingMonth - 1, ob.dayOfMonth);

        // Auto-create the obligation record
        const record = await this.prisma.statutoryPayment.create({
          data: {
            tenantId,
            type: ob.type,
            period,
            amount: 0,
            dueDate,
            status: "PENDING",
          },
        });
        createdRecords.push(record);

        calendar.push({
          type: ob.type,
          label: ob.label,
          period,
          dueDate,
          status: "PENDING",
          amount: 0,
        });
      }
    }

    // Determine overall compliance status
    const overdue = calendar.filter(c => c.status === "PENDING" && new Date(c.dueDate) < now);
    const upcoming = calendar.filter(c => c.status === "PENDING" && new Date(c.dueDate) >= now);
    const paid = calendar.filter(c => c.status === "PAID");

    return {
      period,
      month: targetMonth,
      year: targetYear,
      obligations: calendar,
      summary: {
        total: calendar.length,
        paid: paid.length,
        pending: upcoming.length,
        overdue: overdue.length,
      },
      autoGenerated: createdRecords.length,
    };
  }

  // ── Record Statutory Payment ───────────────────────────────────────────
  async recordStatutoryPayment(
    dto: {
      statutoryPaymentId: string;
      amount: number;
      challanNumber: string;
      paymentDate: string;
      paymentMode: string;
      bankAccountGLCode?: string; // GL code for bank account used, defaults to "1100" (Cash/Bank)
    },
    tenantId: string,
    userId: string,
  ) {
    const payment = await this.prisma.statutoryPayment.findFirst({
      where: { id: dto.statutoryPaymentId, tenantId },
    });
    if (!payment) throw new NotFoundException("Statutory payment record not found");
    if (payment.status === "PAID") throw new BadRequestException("Already paid");

    // Get the liability ledger account for this statutory type
    const liabilityCode = this.ledgerCodeMap[payment.type];
    if (!liabilityCode) throw new BadRequestException(`Unknown statutory type: ${payment.type}`);

    const liabilityAccount = await this.prisma.gLAccount.findFirst({
      where: { tenantId, code: liabilityCode },
    });
    if (!liabilityAccount) throw new BadRequestException(`GL Account ${liabilityCode} not found`);

    // Default bank/cash GL code
    const bankCode = dto.bankAccountGLCode ?? "1100";
    const bankAccount = await this.prisma.gLAccount.findFirst({
      where: { tenantId, code: bankCode },
    });
    if (!bankAccount) throw new BadRequestException(`Bank GL Account ${bankCode} not found. Please provide a valid bankAccountGLCode.`);

    // Post journal: DEBIT liability (clear it), CREDIT bank
    const journalEntry = await this.journalService.createJournal({
      tenantId,
      date: dto.paymentDate,
      narration: `Statutory payment: ${payment.type} for period ${payment.period} | Challan: ${dto.challanNumber}`,
      refType: "STATUTORY_PAYMENT",
      refId: payment.id,
      postedBy: userId,
      lines: [
        {
          ledgerAccountId: liabilityAccount.id,
          type: "DEBIT",
          amount: dto.amount,
          narration: `${payment.type} payment - ${payment.period}`,
        },
        {
          ledgerAccountId: bankAccount.id,
          type: "CREDIT",
          amount: dto.amount,
          narration: `Bank payment for ${payment.type}`,
        },
      ],
    });

    console.log(`[CompliancePayment] ${payment.type} | Period: ${payment.period} | Amount: ${dto.amount} | Challan: ${dto.challanNumber} | JE: ${journalEntry.id}`);

    // Update statutory payment record
    const updated = await this.prisma.statutoryPayment.update({
      where: { id: payment.id },
      data: {
        amount: dto.amount,
        challanNumber: dto.challanNumber,
        paymentDate: new Date(dto.paymentDate),
        paymentMode: dto.paymentMode,
        journalEntryId: journalEntry.id,
        status: "PAID",
      },
    });

    return {
      id: updated.id,
      type: updated.type,
      period: updated.period,
      amount: Number(updated.amount),
      challanNumber: updated.challanNumber,
      paymentDate: updated.paymentDate,
      paymentMode: updated.paymentMode,
      journalEntryId: journalEntry.id,
      status: "PAID",
    };
  }

  // ── Get Statutory Payments ─────────────────────────────────────────────
  async getStatutoryPayments(
    tenantId: string,
    filters?: { type?: string; status?: string; period?: string },
  ) {
    const where: any = { tenantId };
    if (filters?.type) where.type = filters.type;
    if (filters?.status) where.status = filters.status;
    if (filters?.period) where.period = filters.period;

    const payments = await this.prisma.statutoryPayment.findMany({
      where,
      orderBy: [{ dueDate: "desc" }],
    });

    return payments.map(p => ({
      id: p.id,
      type: p.type,
      period: p.period,
      amount: Number(p.amount),
      challanNumber: p.challanNumber,
      paymentDate: p.paymentDate,
      dueDate: p.dueDate,
      paymentMode: p.paymentMode,
      journalEntryId: p.journalEntryId,
      status: p.status,
      createdAt: p.createdAt,
    }));
  }
}
