export const QUALITY_FORMS_MASTER = [
  { code: "DH/TECH/FR/01", title: "Temperature Monitoring Format", category: "DAILY_CHECK", frequency: "DAILY", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/02", title: "Temperature & Humidity Format", category: "DAILY_CHECK", frequency: "DAILY", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/03", title: "Alert Value (Critical Value) Information Format", category: "IQC", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/04", title: "New Reagent Verification Format", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/05", title: "Retest Format", category: "SAMPLE_MANAGEMENT", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/06", title: "Sample Outsource Format", category: "SAMPLE_MANAGEMENT", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/07", title: "Equipment History Card", category: "EQUIPMENT", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/08", title: "ILC / Split Sample Performance Format", category: "IQC", frequency: "QUARTERLY", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/09", title: "Validation Format (Retained Sample)", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/10", title: "Validation Format (Intraday)", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/11", title: "Validation Format — New Kit", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/12", title: "Validation Format — Technical Staff", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/13", title: "Validation Format — Staining", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL"] },
  { code: "DH/TECH/FR/14", title: "Machine Validation Format", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/15", title: "Machine / Manual Validation Format", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/16", title: "Validation Format — Blood Group", category: "VALIDATION", frequency: "PER_EVENT", department: "HAEMATOLOGY", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/17", title: "Validation Format — Urine", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL"] },
  { code: "DH/TECH/FR/18", title: "Validation Format — Culture / Micro", category: "VALIDATION", frequency: "PER_EVENT", department: "MICROBIOLOGY", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/19", title: "IQC Monthly Summary Format", category: "IQC", frequency: "MONTHLY", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/20", title: "IQC Daily Levey-Jennings Format", category: "IQC", frequency: "DAILY", department: "LAB", standards: ["NABL", "CAP", "ISO_15189", "CLSI"] },
  { code: "DH/TECH/FR/21", title: "Reagent / Consumable Log Format", category: "MAINTENANCE", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/22", title: "Sample Rejection Format", category: "SAMPLE_MANAGEMENT", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/23", title: "Complaint / Feedback Register", category: "MANAGEMENT", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/24", title: "Internal Audit Checklist", category: "AUDIT", frequency: "QUARTERLY", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/25", title: "Non-Conformance Report (NCR)", category: "NCR", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/26", title: "CAPA Format", category: "NCR", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/27", title: "Biomedical Waste Disposal Log", category: "SAFETY", frequency: "DAILY", department: "LAB", standards: ["NABL", "BMW_2016"] },
  { code: "DH/TECH/FR/28", title: "Equipment Calibration Record", category: "CALIBRATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/29", title: "Preventive Maintenance Schedule", category: "MAINTENANCE", frequency: "MONTHLY", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/30", title: "Equipment Breakdown Record", category: "EQUIPMENT", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/31", title: "Proficiency Testing (PT/EQAS) Result Format", category: "IQC", frequency: "QUARTERLY", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/32", title: "Staff Training Record", category: "HR", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/33", title: "Competency Assessment Form", category: "HR", frequency: "ANNUAL", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/34", title: "Biosafety Incident Report", category: "SAFETY", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP", "WHO"] },
  { code: "DH/TECH/FR/35", title: "Needlestick Injury Report", category: "SAFETY", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP", "OSHA"] },
  { code: "DH/TECH/FR/36", title: "Chemical Spillage Record", category: "SAFETY", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/37", title: "Hand Hygiene Observation Form", category: "SAFETY", frequency: "MONTHLY", department: "LAB", standards: ["NABL", "WHO"] },
  { code: "DH/TECH/FR/38", title: "Turnaround Time Monitoring Format", category: "MANAGEMENT", frequency: "MONTHLY", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/39", title: "Critical Values Log", category: "IQC", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
  { code: "DH/TECH/FR/40", title: "Reference Range Verification Format", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CLSI"] },
  { code: "DH/TECH/FR/41", title: "Uncertainty of Measurement Calculation Sheet", category: "IQC", frequency: "ANNUAL", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/42", title: "Method Comparison / Correlation Format", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CLSI"] },
  { code: "DH/TECH/FR/43", title: "Linearity Verification Format", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CLSI", "CAP"] },
  { code: "DH/TECH/FR/44", title: "Carry-Over Study Format", category: "VALIDATION", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CLSI"] },
  { code: "DH/TECH/FR/45", title: "Autoclave Monitoring Log", category: "MAINTENANCE", frequency: "DAILY", department: "MICROBIOLOGY", standards: ["NABL", "WHO"] },
  { code: "DH/TECH/FR/46", title: "Blood Culture Contamination Rate Format", category: "IQC", frequency: "MONTHLY", department: "MICROBIOLOGY", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/47", title: "Stool Parasite Examination Format", category: "MICROBIOLOGY", frequency: "PER_EVENT", department: "MICROBIOLOGY", standards: ["NABL", "WHO"] },
  { code: "DH/TECH/FR/48", title: "Cytology / Histopathology Specimen Log", category: "SAMPLE_MANAGEMENT", frequency: "PER_EVENT", department: "HISTOPATHOLOGY", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/49", title: "Molecular Lab Access Log", category: "SAFETY", frequency: "DAILY", department: "MOLECULAR", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/50", title: "Management Review Meeting Minutes", category: "MANAGEMENT", frequency: "ANNUAL", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/51", title: "Supplier / Vendor Evaluation Form", category: "MANAGEMENT", frequency: "ANNUAL", department: "LAB", standards: ["NABL", "ISO_15189"] },
  { code: "DH/TECH/FR/52", title: "Patient Consent Form — Laboratory Tests", category: "MANAGEMENT", frequency: "PER_EVENT", department: "LAB", standards: ["NABL", "CAP"] },
  { code: "DH/TECH/FR/53", title: "External Quality Assessment (EQAS) Report", category: "IQC", frequency: "QUARTERLY", department: "LAB", standards: ["NABL", "CAP", "ISO_15189"] },
] as const;

export type QualityFormMasterItem = {
  code: string;
  title: string;
  category: string;
  frequency: string;
  department: string;
  standards: string[];
};
